### ISSUE TITLE
Bar component prop radius doesn't accepts an array of int as in v1.8.5

### ISSUE THREAD

**Issue by matheusmb** [recharts/recharts#2335]
- [x] I have searched the [issues](https://github.com/recharts/recharts/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recharts-issue-template-forked-tvlud?file=/src/index.tsx)

### Steps to reproduce
Setting prop radius of Bar component to `radius={[0, 10, 10, 0]}` generates typescript error: 

`<Bar dataKey="value" fill="#8884d8" radius={[0, 10, 10, 0]}>`
```
No overload matches this call.
  Overload 2 of 2, '(props: Props, context: any): Bar', gave the following error.
```

### What is expected?
The bars with top right and bottom right corners with radius

### What is actually happening?
Typescript build error

| Environment | Info |
|---|---|
| Recharts | v2.0.0-beta.8 |
| React | react v17.0.1 |
| System | Win 10 Pro |
| Browser | Edge Chromium v88 |

---
The same code works perfectly on v1.8.5

**Comment by dillonreedy** [comment]
This is some kind of weird CodeSandbox-Typescript-compilation error. It's not getting the correct prop type definitions in the declaration file.

I've created a branch using your exact code in the demo project, and it works just fine [here](https://github.com/dillonreedy/recharts/tree/bar-radius-demo). I only changed around the data that's used.

All you have to do to run it is:
1. Execute the command "npm run build"
2. Execute the command "npm run-script demo"
3. Navigate to localhost:3000 and click on the Bar Chart link to see your demo working there

Now if you ctrl-click on the Radius prop in Code Sandbox you can see that the allowable prop types are "number | string"
![image](https://user-images.githubusercontent.com/3454995/101233367-26394a00-367e-11eb-9861-7c52e0db60fa.png)

While ctrl-clicking on the Radius prop in the demo project, you can see that the allowable prop types are "number | ReadonlyArray<number>"
![image](https://user-images.githubusercontent.com/3454995/101233444-88924a80-367e-11eb-89a7-703702d2233c.png)

**Comment by matheusmb** [comment]
Hi @dillonreedy, locally I'm using yarn and I receive the same error as in the sandbox with `yarn start` and as well with `yarn build`.
I rolled back to v1.8.5 and I didn't receive the errors anymore.

**Comment by Rabter1** [comment]
I have the exact same issue locally on my machine with npm and recharts 2.0.2

I try to only set the radius of the bars in a bar chart. (Without luck so far...)
The definition is different from the one mentioned by @dillonreedy 
![image](https://user-images.githubusercontent.com/33700346/104355586-30672780-550b-11eb-9320-a6bd5eb113c7.png)

**Comment by Kjagd** [comment]
@xile611 Could you reopen this, as the type is still bad in 2.0.3?

The issue seems to be related to the `RectangleProps & PresentationAttributes<SVGPathElement>` being an intersection type, causing the resulting type to be this:

![image](https://user-images.githubusercontent.com/1812228/104889455-8e15cc80-596e-11eb-9614-2372f644cd2b.png)

As mentioned [here](https://github.com/recharts/recharts/issues/1792#issuecomment-647917011), one solution could be to Omit the radius type from the SVG type. Or alternatively using an interface:
```
export declare interface Props extends PresentationAttributes<SVGPathElement> {
      radius?: number | RectRadius;
      ...
}
```

**Comment by avindra** [comment]
#2398 indicates that there was an error in publishing 2.0.3

**Comment by kodermax** [comment]
I have the same error.
![image](https://user-images.githubusercontent.com/590985/107192282-7fb35180-69fe-11eb-9947-22f359865998.png)
