### ISSUE TITLE
Charts crash under Vite 8 (Rolldown) — `es-toolkit/compat/*` default imports resolve to CommonJS (`require_isUnsafeProperty is not a function`)

### ISSUE THREAD

**Issue by masenf** [recharts/recharts#7376]
## What is the current behavior?

Importing/rendering any chart from `recharts` 3.8.1 in an app bundled with **Vite 8** (which uses **Rolldown**) crashes at runtime, because recharts default-imports several `es-toolkit` helpers through their per-function `compat` subpaths:

```ts
// src/util/ChartUtils.ts, src/util/DataUtils.ts, src/cartesian/CartesianAxis.tsx, src/polar/Pie.tsx, ...
import get from 'es-toolkit/compat/get';
import sortBy from 'es-toolkit/compat/sortBy';
import throttle from 'es-toolkit/compat/throttle';
// also: range, omit, last, maxBy, minBy, sumBy, uniqBy
```

Under es-toolkit's `exports` map the `./compat/*` subpath has **no ESM (`import`) condition**, so each of these resolves to a CommonJS shim:

```js
// node_modules/es-toolkit/compat/get.js
module.exports = require('../dist/compat/object/get.js').get;
```

These shims are used by recharts' core utilities (`ChartUtils`, `DataUtils`, …), so essentially **every chart** pulls CommonJS into the module graph. Rolldown's CJS→ESM interop helper then ends up in a chunk that executes before it is initialized, and the page crashes:

- **dev server:** `Uncaught TypeError: require_isUnsafeProperty is not a function`
- **production build (minified):** `TypeError: t is not a function`

(In React Router apps this also causes an infinite route-reload loop, since the failed route module is retried indefinitely.)

## What is the expected behavior?

Rendering a chart works under Vite 8 / Rolldown, the same as it does with earlier bundlers — no CommonJS interop helper is pulled into the bundle, and no runtime `TypeError`.

## Please provide a demo of the problem in a sandbox

Minimal reproduction (three files). It crashes in the browser via both `npm run dev` and `npm run build && npm run preview`:

**`package.json`**
```json
{
  "name": "recharts-vite8-repro",
  "private": true,
  "type": "module",
  "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" },
  "dependencies": {
    "react": "19.2.6",
    "react-dom": "19.2.6",
    "recharts": "3.8.1",
    "vite": "8.0.12"
  }
}
```

**`index.html`**
```html
<!doctype html>
<html>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
```

**`src/main.js`**
```js
import { createElement } from "react";
import { createRoot } from "react-dom/client";
import { LineChart, Line } from "recharts";

const data = [{ x: 1 }, { x: 2 }, { x: 3 }];
createRoot(document.getElementById("root")).render(
  createElement(LineChart, { width: 300, height: 200, data },
    createElement(Line, { dataKey: "x" }))
);
```

`npm install && npm run dev`, then open the page → blank page, and the console shows `Uncaught TypeError: require_isUnsafeProperty is not a function`.

**Deterministic check without a browser** — build a single chart import as a library and run it under Node:

```js
// src/main.js
import { LineChart } from "recharts";
console.log(typeof LineChart);
```
```js
// vite.config.mjs
import { defineConfig } from "vite";
export default defineConfig({
  build: {
    minify: false,
    lib: { entry: "src/main.js", formats: ["es"], fileName: "repro" },
    rollupOptions: { external: ["react", "react-dom", "react/jsx-runtime"] },
  },
});
```
```bash
npm run build && node dist/repro.js
```
```
.../dist/repro.js:735
	var require_isUnsafeProperty = require_isUnsafeProperty();
	                               ^
TypeError: require_isUnsafeProperty is not a function
```

The same failure is reachable through the dev dependency optimizer too: after Vite pre-bundles recharts, `node_modules/.vite/deps/recharts.js` throws the identical error.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

- recharts **3.8.1**
- es-toolkit **1.47.0** (installed transitively)
- vite **8.0.12** (Rolldown)
- react / react-dom **19.2.x**, Node 22

It is a bundler/module-initialization crash rather than a rendering issue, so it reproduces in any browser and in Node (Linux, also reported on Windows). It is specific to **Vite 8 / Rolldown** — both the dev pre-bundle and the production build. The `es-toolkit/compat/*` default-import pattern is present throughout recharts 3.x, so earlier 3.x releases are likely affected as well when built with Vite 8.

---

## Root cause

The per-function `es-toolkit/compat/*` entry points are CommonJS shims (`module.exports = require(...)`). Rolldown wraps them in a CJS-interop helper and, when code-splitting, can place that helper in a chunk whose initialization isn't ordered before the consuming chunk — so the helper is referenced before it exists. (Rollup + `@rollup/plugin-commonjs` in earlier Vite versions handled this differently, which is why it surfaces specifically on Vite 8 / Rolldown.)

The `es-toolkit/compat` **barrel** does provide an ESM condition (`"import" → ./dist/compat/index.mjs`, pure ESM) and re-exports all of these helpers as named exports:

```jsonc
// es-toolkit@1.47.0 package.json
"./compat/*": { "default": { "default": "./compat/*.js" } },                 // CJS only
"./compat":   { "import": { "default": "./dist/compat/index.mjs" }, ... }    // ESM available
```

## Suggested fix

Switch the per-function default imports to named imports from the `es-toolkit/compat` barrel:

```diff
-import get from 'es-toolkit/compat/get';
+import { get } from 'es-toolkit/compat';
```

This keeps recharts' module graph ESM-only, so Rolldown never emits the CJS-interop helper. Behavior is unchanged (same `compat` functions) and tree-shaking is preserved (`es-toolkit/compat` is `sideEffects: false`).

A patch applying this across the affected files (`get`, `last`, `maxBy`, `minBy`, `omit`, `range`, `sortBy`, `sumBy`, `throttle`, `uniqBy`), verified locally to fix both the dev optimizer and the production build:

https://github.com/recharts/recharts/compare/main...masenf:recharts:esm-compat-imports

## Is there a better fix?

Before opening a PR I wanted to check whether you'd prefer a different direction:

1. The barrel-import change above (recharts-side, minimal, behavior-preserving), **or**
2. Moving these call sites off the `compat` layer to es-toolkit's main ESM API where the semantics already match, **or**
3. Treating this as an **es-toolkit** issue — asking them to add an `import`/ESM condition to the `./compat/*` subpath exports — so the per-function imports resolve to ESM with no recharts change.

Is there a reason the per-function `compat` subpaths are preferred today (e.g. bundle size)? In my testing the barrel import tree-shakes to the same set of helpers, so I didn't see a downside — but you'll know the constraints better than I do. Happy to send a PR for whichever approach you favor.

**Comment by PavelVanecek** [comment]
So we used to have that other style of imports and then switched it in https://github.com/recharts/recharts/pull/5926

@dayongkr is this something on your radar?

**Comment by marcellio4** [comment]
@PavelVanecek  not sure what have you done guys in the new version but i have same issue on Vite 8 and when i downgrade your recharts to 3.7.2 then that fixed it. no errors anymore. So it seems you guys have broke something in your latest release.

**Comment by PavelVanecek** [comment]
Are you thinking 3.7.0 @marcellio4 ? I will try to reproduce and see what happened.

**Comment by marcellio4** [comment]
@PavelVanecek this is my dependecy "recharts": "^3.7.2", and everything works soon as i upgrade to 3.8.1 it was broken and i had that error but i just retried now with upgrade vite vite  8.0.0 - 8.0.14 and i did rollback the recharts to the LTS 3.8.1 and it seems working no errors anymore. It is very weird. So even after uninstall nodes module and running all again it seems all working.

**Comment by GavinPlusPlus** [comment]
Just adding in here. I'm having the same issue with `vite@8.0.14` and `recharts@3.8.1`. One difference though is for some reason I am able to get it working within the dev server, it's just the production build that throws the same `TypeError: t is not a function` error for me. With minify off it instead outputs `TypeError: require_get is not a function`

**Comment by jakejarvis** [comment]
Upstream issue: https://github.com/toss/es-toolkit/issues/1740

FYI, `"overrides": { "es-toolkit": "1.46.1" }` works as a quick fix for now.

**Comment by PavelVanecek** [comment]
Thanks everyone for the details. I tried to reproduce in https://github.com/recharts/recharts-integ/pull/95 but it works! What am I missing?

**Comment by jakejarvis** [comment]
@PavelVanecek hmm, my guess would be something to do with code splitting not being triggered in the right way but the inner workings of vite/rolldown are a bit of a mystery to me to be honest! I do have recharts included in my [`optimizeDeps` list](https://vite.dev/config/dep-optimization-options#optimizedeps-include) in a project with this problem, not sure about others here?

**Comment by PavelVanecek** [comment]
@jakejarvis if you would like to try and reproduce the problem in recharts-integ it will then work as regression test. We run these on every PR, including dependency bumps

**Comment by masenf** [comment]
@PavelVanecek it seems the issue is fixed (at least partially) in vite@8.0.14, so the reproducer doesn't hit the issue...

If i down pin the integration test to 8.0.13 or 8.0.12 then I do hit the `require_isUnsafeProperty is not a function` trace in dev mode and the `t is not a function` in build/preview

I believe the fix was in rolldown 1.0.2

> cjs: rename CJS-wrapped locals that would shadow chunk-scope names ([#9392](https://github.com/rolldown/rolldown/pull/9392)) by hyf0

https://github.com/rolldown/rolldown/releases/tag/v1.0.2

**Comment by GavinPlusPlus** [comment]
@masenf I guess it being partially fixed in vite@8.0.14 explains why I was struggling with it in dev and build yesterday, and then just in the build today after I bumped vite up. Saved my sanity today once I found this issue, was a bit perplexed at first. Anyone else able to reproduce the same on 8.0.14 with it only failing after a build/preview? Going to try and reproduce it tomorrow.

**Comment by PavelVanecek** [comment]
Still works with vite 8.0.13. Sounds to me like we're done here and we can close this?

https://github.com/recharts/recharts-integ/pull/95/changes#diff-e881bcd7311360738ca257cb46f9bbe6498dc2ce2e0d1552bb251a3406abd34b

**Comment by ZipBrandon** [comment]
I am still getting 
```
CartesianChart-DyuC0tCE.js:3 Uncaught TypeError: t is not a function
    at CartesianChart-DyuC0tCE.js:3:1334
    at chunk-Do4u16f7.js:1:421
    at CartesianChart-DyuC0tCE.js:3:9102
    at chunk-Do4u16f7.js:1:421
    at CartesianChart-DyuC0tCE.js:3:9596
    at chunk-Do4u16f7.js:1:421
    at CartesianChart-DyuC0tCE.js:3:9753
    at chunk-Do4u16f7.js:1:421
    at CartesianChart-DyuC0tCE.js:3:9792
```
with
```
├── recharts@3.8.1

rolldown@1.0.3
└─┬ vite@8.0.16
```

**Comment by PavelVanecek** [comment]
Still can't reproduce, works perfectly fine on my laptop and in github CI too: https://github.com/recharts/recharts-integ/pull/96

delete your node_modules and reinstall
