### ISSUE TITLE
How to specify tickFormatter with v3?

### ISSUE THREAD

**Issue by Etsija** [recharts/recharts#6010]
With 2.x, I was able to specify tickFormatter for radar charts like this:
```typescript
            <PolarAngleAxis
              dataKey='component'
              tickFormatter={(value) => {
                return value === 'Base'
                  ? 'Base'
                  : value === 'Temporal'
                    ? 'Temp'
                    : value.slice(0, 3);
              }}
            />
```
but with v3, I get an error
```
value.slice is not a function
```

Similarly, earlier I could do for the bar charts this:
```typescript
              <XAxis
                type='number'
                dataKey='score'
                domain={[0, 100]}
                tickFormatter={(value) => `${value}%`}
              />
```
but now I get
```
Warning: [DecimalError] Invalid argument: undefined
```

Documentation of tickFormatter really isn't helpful, so what should I change?

**Comment by Etsija** [comment]
Actually, the second failure example is probably due to the bug described in #6011.

**Comment by ckifer** [comment]
Will take a look at both thanks for the report

**Comment by ckifer** [comment]
PR is up to solve #6011

---

`tickFormatter` is specified the same way it has been

```tsx
            tickFormatter={(value) => {
              return value;
            }}
```

Can you make a reproduction for your issue above?

**Comment by ckifer** [comment]
Ah I was able to reproduce https://stackblitz.com/edit/react-gmamwjuu?file=src%2FExample.tsx&showSidebar=0

It looks like `tickFormatter` is being passed the index of the ticks the render before the value

so `0, 1, 2, 3, 4, 5..`

and then the string values. Will look at fixing 

cc @PavelVanecek
