### ISSUE TITLE
Underlying Redux Dependencies Cause Dev Build Failures

### ISSUE THREAD

**Issue by AlexHartford** [recharts/recharts#6117]
## What is the current behavior?

Similar to https://github.com/recharts/recharts/issues/5562, I'm running into issues with recharts using redux / @reduxjs/toolkit under the hood. The culprit is changing my next.js application to use `next.config.ts` from `next.config.js`.

```
 ⨯ Error: require() of ES Module /redacted/node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs not supported.
Instead change the require of /redacted/node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs to a dynamic import() which is available in all CommonJS modules.
    at @reduxjs/toolkit (.next/server/pages/_app.js:4264:18)
    at (pages-dir-node)/./packages/redacted/node_modules/recharts/lib/state/layoutSlice.js (.next/server/vendor-chunks/recharts.js:1050:1)
    at (pages-dir-node)/./packages/redacted/node_modules/recharts/lib/context/chartLayoutContext.js (.next/server/vendor-chunks/recharts.js:650:1)
    at (pages-dir-node)/./packages/redacted/node_modules/recharts/lib/component/Legend.js (.next/server/vendor-chunks/recharts.js:500:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

Notably, this is only an issue when trying to local dev with webpack, turbopack works fine.

## What is the expected behavior?

Underlying redux deps shouldn't error out.

## Please provide a demo of the problem in a sandbox

Here is how: https://github.com/recharts/recharts/wiki/How-to-share-a-demo

Happy to provide a demo if necessary, but I believe the root cause can be understood without one.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?
3.1.0, and have tried reverting back to previous versions with no luck.
React 19, Next 15

**Comment by ckifer** [comment]
> next.config.ts from next.config.js.

We have integration tests for Next 15 and generally everything is green. Is this change something new from next recently? Doesn't really make sense that changing your config file from js to ts would cause this to break

what does `npm ls @reduxjs/toolkit` print?

**Comment by AlexHartford** [comment]
> We have integration tests for Next 15 and generally everything is green. Is this change something new from next recently? Doesn't really make sense that changing your config file from js to ts would cause this to break

The change is specifically when changing from a javascript config file to a typescript config file, rather than going from 14 to 15.

> 
> what does `npm ls @reduxjs/toolkit` print?

```
@company/redacted@1.0.0 -> ./packages/redacted
  └─┬ recharts@3.1.0
    └── @reduxjs/toolkit@2.8.2
```

**Comment by ckifer** [comment]
> The change is specifically when changing from a javascript config file to a typescript config file

Right, that doesn't make much sense. Typescript or not shouldn't change anything. Especially not change if esm is required or not. 

Do you have type: module in your package.json?

Can you paste a redacted tsconfig?
I know you said a repro isn't necessary but we might need one if it's something specific to your config

**Comment by ckifer** [comment]
I can create a brand new next project (with a TS config file), add recharts@latest, add a chart, run the dev server, and run a successful build without issues. What part of your build is failing?

```
> next build

   ▲ Next.js 15.3.4

   Creating an optimized production build ...
 ✓ Compiled successfully in 2000ms
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
 ✓ Generating static pages (5/5)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                                 Size  First Load JS    
┌ ○ /                                    99.5 kB         201 kB
└ ○ /_not-found                            977 B         102 kB
+ First Load JS shared by all             101 kB
  ├ chunks/4bd1b696-3cf3f302025e6e7d.js  53.2 kB
  ├ chunks/684-91112248fb019c20.js       45.9 kB
  └ other shared chunks (total)          1.93 kB


○  (Static)  prerendered as static content
```

**Comment by AlexHartford** [comment]
> Do you have type: module in your package.json?

Yes, also tried without it

> I can create a brand new next project (with a TS config file), add recharts@latest, add a chart, run the dev server, and run a successful build without issues. What part of your build is failing?

It's actually only `next dev` that fails after the compilation step (runtime error).

Thank you for your prompt responses!

**Comment by ckifer** [comment]
No runtime errors here. There has to be another setting messing with things. Can you paste your tsconfig?

**Comment by AlexHartford** [comment]
> No runtime errors here. There has to be another setting messing with things. Can you paste your tsconfig?

```
{
  "compilerOptions": {
    "target": "ES6",
    "lib": ["dom", "ES2016", "ES2017.Object", "ES2020", "ES2021.String"],
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "module": "esnext",
    "moduleResolution": "bundler",
    "noEmit": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "paths": {
      "@company/redacted": ["packages/redacted/src/index"],
      "@company/redacted/*": ["packages/redacted/src/*"],
      "@company/redacted2": ["packages/redacted2/src/index"],
      "@company/redacted2/*": ["packages/redacted2/src/*"],
      "src/*": ["src/*", "packages/redacted/src/*", "packages/redacted2/src/*"],
    },
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "useUnknownInCatchVariables": false,
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "ts-node": {
    "compilerOptions": {
      "module": "CommonJS"
    }
  },
  "include": [
    "next-env.d.ts",
    "instrumentation.ts",
    "**/*.ts",
    "**/*.tsx",
    ".storybook/**/*"
  ],
  "exclude": [
    "node_modules",
    "packages/**/*",
    ".next",
  ]
}

```

**Comment by ckifer** [comment]
out for the week but I'll get back to this

**Comment by iffa** [comment]
I am also encountering this issue, not in local dev but when the app is built (local dev uses turbopack, prod build doesn't) and then run. Every page that uses recharts crashes with this error. The app is built for a Docker container using output: standalone, and if I run next build locally, I can see indeed that those files are missing, the redux toolkit directory only contains cjs variants. Same goes for depndencies of redux toolkit such as redux.

**Comment by iffa** [comment]
Adding the following to `next.config.js` fixed issues for me (but obviously not ideal...):

```
  outputFileTracingIncludes: {
    "*": [
      "../../node_modules/@reduxjs/toolkit/dist/**/*",
      "../../node_modules/immer/dist/**/*",
      "../../node_modules/reselect/dist/**/*",
      "../../node_modules/redux/dist/**/*",
      "../../node_modules/redux-thunk/dist/**/*",
    ],
  },
```

Paths are relative to monorepo root where node_modules is (we're using yarn v4)

**Comment by ckifer** [comment]
@iffa do you know how to reproduce? I still haven't been able to

**Comment by iffa** [comment]
> @iffa do you know how to reproduce? I still haven't been able to

Not really, I just updated recharts to v3 in my existing app that lives in a yarn v4 monorepo, using Next.js 15.4.4 and using turbopack in dev server only, where the issue is not present. As said, we have output: standalone for our builds inside Docker, but from the files I could see that tehe issue is aldo present for local builds. If I disabled turbopack for dev I would most likely get it for dev server as well. Not even sure where to start with this, but i can share our next.config.js file later

**Comment by ckifer** [comment]
That would be helpful, thanks

**Comment by iffa** [comment]
Alright sorry I didn't come back to this. We were actually getting a different error than Alex: `Cannot find module '/app/node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs'`. Our app is (should be) ESM, but for some reason CJS versions of redux are bundled, but recharts is wanting to import from that path. It then doesn't exist and everything breaks. As said, I managed to fix this for our output: standalone Next.js builds with something along the lines of this in our next.config file:

```
  outputFileTracingRoot: tracingRoot,
  outputFileTracingIncludes: {
    "*": [
      "../../node_modules/@reduxjs/toolkit/dist/**/*",
      "../../node_modules/immer/dist/**/*",
      "../../node_modules/reselect/dist/**/*",
      "../../node_modules/redux/dist/**/*",
      "../../node_modules/redux-thunk/dist/**/*",
    ],
  },
```

The dependencies of redux-toolkit also needed to be included, because the issue just kept on going deeper down.

Here's a (slightly cleaned up & redacted) Next.js config file that we have in our project:

```
import path from "path";
import { fileURLToPath } from "url";
import { withSentryConfig } from "@sentry/nextjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const tracingRoot = path.join(__dirname, "../../");

/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,
  output: "standalone",

  allowedDevOrigins: ["..."],
  poweredByHeader: false,

  experimental: {
    swcPlugins: [["@lingui/swc-plugin", {}]],
  },


  outputFileTracingRoot: tracingRoot,
  outputFileTracingIncludes: {
    "*": [
      "../../node_modules/@reduxjs/toolkit/dist/**/*",
      "../../node_modules/immer/dist/**/*",
      "../../node_modules/reselect/dist/**/*",
      "../../node_modules/redux/dist/**/*",
      "../../node_modules/redux-thunk/dist/**/*",
    ],
  },

  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: { ignoreDuringBuilds: true },

  transpilePackages: ["@foo/auth", "@foo/common", "@foo/bar-common"],

  /**
   * This is used for dev server (turbopack)
   */
  turbopack: {
    rules: {
      "*.po": {
        loaders: ["@lingui/loader"],
        as: "*.js",
      },
    },
  },

  /**
   * Used for builds until turbopack for builds is stable
   */
  webpack: (config) => {
    /**
     * @see https://github.com/lingui/js-lingui/issues/1782
     */
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
    config.module.rules.push({
      test: /\.po$/,
      use: {
        loader: "@lingui/loader",
      },
    });

    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    return config;
  },

  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },
};

let finalConfig = config;

if (process.env.NODE_ENV === "production" && process.env.WITH_SENTRY_CONFIG) {
  finalConfig = withSentryConfig(config, {
   // irrelevant sentry configuration
  });
}

export default finalConfig;
```

**Comment by rajtersimon** [comment]
I have the same issue. In sentry I can see this error: 

```
Cannot find module '/app/node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs'
```

My versions:
- recharts: 3.1.0
- next.js: 15.4.1
- react: 19.1.0

And it was working before, not sure which version excatly. It works in dev, there are no build time errors, the error just occurs in runtime when I try to access a route that uses recharts.

**Comment by ckifer** [comment]
what package managers do you all use? Do you all use webpack for builds? Nothing I'm trying has any issues

**Comment by AlexHartford** [comment]
> what package managers do you all use? Do you all use webpack for builds? Nothing I'm trying has any issues

npm, webpack for builds, turbopack for local dev (which works fine)

**Comment by ckifer** [comment]
you all have `use client;` in your components with charts right?

---

trying to reproduce with the following

* recharts: 3.1.2
* next.js: 15.3.4
* react/react-dom: 19.1.0

I've tried downgrading recharts then upgrading to 3.x

> turbopack for local dev (which works fine)

So are you saying the actual steps to reproduce are `npm run build && npm run start`? or am I missing something?

Do you have redux installed in your project besides recharts at all?

**Comment by AlexHartford** [comment]
> you all have `use client;` in your components with charts right?

My project is still on pages dir, so N/A

> So are you saying the actual steps to reproduce are `npm run build && npm run start`? or am I missing something?

For me specifically, `next dev` is the repro. It's not a build issue, just a runtime issue.

> Do you have redux installed in your project besides recharts at all?

Nope

**Comment by ckifer** [comment]
> My project is still on pages dir

this might be it

> turbopack for local dev (which works fine)
> next dev is the repro

I'm confused, isn't `next dev` what you use for local dev? what works fine? 😅

**Comment by iffa** [comment]
> what package managers do you all use? Do you all use webpack for builds? Nothing I'm trying has any issues

- yarn v4 monorepo with node_modules, not pnp
- Pages directory, no app router / rsc
- turbopack is only enabled in dev (next dev --turbopack), prod builds use webpack (not turbopack)
  - and again, for me, the issue occurs ONLY in prod builds, dev works fine

**Comment by ckifer** [comment]
_insert confused gif here_

All of this tested upgrading from 2.15.4 to 3.1.3 with similar next config and TS config to the above listed

* pages directory works
* npm works
* yarn 
* `next dev` and `next dev --turbopack` work
* `next build` and `next start` (prod build) also works

I'm really not sure what to do 😓, I need a repro

**Comment by ckifer** [comment]
do this for testing purposes only but can someone try deleting their `node_modules` and lockfile? Wondering if something is messed up in the lockfile and nuking things resolves it. That would at least narrow it down

**Comment by AlexHartford** [comment]
> do this for testing purposes only but can someone try deleting their `node_modules` and lockfile? Wondering if something is messed up in the lockfile and nuking things resolves it. That would at least narrow it down

I run into a new error, so it's possible that does fix it.

<img width="972" height="362" alt="Image" src="https://github.com/user-attachments/assets/8020c3af-6a21-434e-9847-daf2a48986d8" />

**Comment by ckifer** [comment]
@dayongkr any ideas on this es-toolkit compat issue?

**Comment by dayongkr** [comment]
@AlexHartford  Could you share the reproducible project repository, if available? I need it for debugging purposes.

**Comment by dayongkr** [comment]
In this setup: "next": "15.4.6", "react": "19.1.0", "react-dom": "19.1.0", "recharts": "^3.1.2", the following code works fine in dev mode with Turbo disabled!

```tsx
import { Trapezoid } from "recharts";

export default function Home() {
  return (
    <svg>
      <Trapezoid
        fill="#8884d8"
        upperWidth={100}
        lowerWidth={60}
        height={50}
        x={50}
        y={50}
        onClick={() => {
          console.log("clicked");
        }}
        isUpdateAnimationActive={true}
        animationBegin={1000}
      />
    </svg>
  );
}
```

**Comment by dayongkr** [comment]
It would be great if you could also share the problematic code!

**Comment by ckifer** [comment]
Thanks @dayongkr - I'll tag you again if we repro. Was just checking if anything stuck out from the error. 

Something's up with module resolution but only in certain circumstances

**Comment by dayongkr** [comment]
Yes I agree! Tag me again if needed😊

**Comment by CloutProject** [comment]
I’ve been running into this issue ever since upgrading `recharts` from version 2.x to 3.x. I had to downgrade back to 2.x to make it work.

To reproduce:
- Use official Next.js docker example: `npx create-next-app --example with-docker nextjs-docker`
- In Dockerfile, replace node version with 20.19.3
- Add the latest version of `recharts` as a dependency.
- Render a `recharts` chart on any page.
- Build and run your container: `docker build -t nextjs-docker . && docker run -p 3000:3000 nextjs-docker`
- Will most likely crash during build, otherwise visit the page containing the `recharts` chart and page will crash.

**Comment by ckifer** [comment]
Thanks for the repro steps will try to look into it when I have a few moments

**Comment by AlexHartford** [comment]
> I’ve been running into this issue ever since upgrading `recharts` from version 2.x to 3.x. I had to downgrade back to 2.x to make it work.
> 
> To reproduce:
> 
> * Use official Next.js docker example: `npx create-next-app --example with-docker nextjs-docker`
> * In Dockerfile, replace node version with 20.19.3
> * Add the latest version of `recharts` as a dependency.
> * Render a `recharts` chart on any page.
> * Build and run your container: `docker build -t nextjs-docker . && docker run -p 3000:3000 nextjs-docker`
> * Will most likely crash during build, otherwise visit the page containing the `recharts` chart and page will crash.

This tracks with me, that's the node version we're running

**Comment by ColdDev** [comment]
> Thanks for the repro steps will try to look into it when I have a few moments

Hi @ckifer, just wanted to add that I am also running into this issue as well. More interestingly, I have noticed that this seems to only happen on a production Next.js build with `output: standalone`.

I have no issues in a development environment, and if I build my Next.js website without `output: standalone`, things work great.

The error I'm encountering looks like so, this is shown on any page that shows a recharts chart, accompanied by a big `500 | Internal Server Error`.

`[Error: Cannot find module '/app/node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs']`

Please let me know if I can be of any help in further investigation :)

**Comment by ckifer** [comment]
I'm not really sure what to say, but every single one of these steps I cannot reproduce the issue 😓 

With docker, I get a perfectly rendering chart with that specific node version

With output `standalone` (which the docker example also has) I also get a perfectly running chart. What I need to know from the folks that have the issue is what version exactly of recharts were you on before upgrading to 3.x?

And are there any other settings you are using that you think might be interfering with this?

**Comment by ckifer** [comment]
@CloutProject - you said you can repro via the steps you laid out. Can you try them again? I'm not sure how docker could fail for you but not for me. What is every single step you took to get it to failure?

**Comment by ColdDev** [comment]
@ckifer

> With output `standalone` (which the docker example also has) I also get a perfectly running chart. What I need to know from the folks that have the issue is what version exactly of recharts were you on before upgrading to 3.x?

I was using `2.15.2` but now I'm using `2.15.4` after downgrading from recharts 3 to recharts 2 to temporarily resolve the issue.

> And are there any other settings you are using that you think might be interfering with this?

I don't believe so? The code I am using for setting up the Recharts graph looks like this:

```tsx

                                        <ResponsiveContainer
                                            width={"100%"}
                                            height={300}
                                        >
                                            <AreaChart
                                                width={300}
                                                height={300}
                                                data={
                                                    analytics.playerCount as any
                                                }
                                                margin={{
                                                    top: 10,
                                                    right: 30,
                                                    left: 0,
                                                    bottom: 0,
                                                }}
                                            >
                                                <CartesianGrid
                                                    strokeDasharray="3 3"
                                                    stroke="#555"
                                                />
                                                <XAxis
                                                    dataKey="name"
                                                    stroke={"#999"}
                                                    tickFormatter={(name) =>
                                                        name.substring(11, 16)
                                                    }
                                                />
                                                <YAxis stroke={"#999"} />
                                                <RechartsTooltip
                                                    contentStyle={{
                                                        backgroundColor: "#333",
                                                        border: "1px solid #555",
                                                        borderRadius: "10px",
                                                        color: "#fff",
                                                    }}
                                                />
                                                <Area
                                                    type="monotone"
                                                    dataKey="Player Count"
                                                    stroke={"#fb8464"}
                                                    fill={"#fb8464"}
                                                    fillOpacity={0.15}
                                                    strokeOpacity={1}
                                                />
                                            </AreaChart>
                                        </ResponsiveContainer>
```

Is this at all helpful?

**Comment by ckifer** [comment]
Thanks - helpful yes, though I don't think it will allow me to reproduce the issue unfortunately. 

I will keep trying but if anyone has anything concrete or contrived please let me know

**Comment by alexjamesmacpherson** [comment]
I am also seeing this issue, and concur with @ColdDev that it only seems to occur for `output: standalone` builds of the app.

If I build the app locally with `output: undefined`, then run with `npm run start`, the pages with charts work absolutely fine. If I build locally with `output: standalone`, then run with `node .next/standalone/server.js`, the pages with charts fail to load with the error `Cannot find module '/app/node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs'`. Note that I didn't need to run anything in Docker to observe this issue.

We're running the latest versions of Next (v15.5.3 w/ pages router) and Recharts (v3.2.0), but still on React v18.3.1. We've only just installed Recharts in the repo, so I can't speak to a prior working version 😕 

The workaround @iffa mentioned above also appears to solve the issue in our case (though notably with the paths adjusted per our repo structure).

> Adding the following to next.config.js fixed issues for me (but obviously not ideal...):
>
> ```
>   outputFileTracingIncludes: {
>     "*": [
>       "../../node_modules/@reduxjs/toolkit/dist/**/*",
>       "../../node_modules/immer/dist/**/*",
>       "../../node_modules/reselect/dist/**/*",
>       "../../node_modules/redux/dist/**/*",
>       "../../node_modules/redux-thunk/dist/**/*",
>     ],
>   },
> ```

**Comment by ckifer** [comment]
> run with node .next/standalone/server.js

@alexjamesmacpherson I can't get this to work for me in general, any tips? All I get is a white screen, no errors

**Comment by ColdDev** [comment]
> > run with node .next/standalone/server.js
> 
> [@alexjamesmacpherson](https://github.com/alexjamesmacpherson) I can't get this to work for me in general, any tips? All I get is a white screen, no errors

Are you checking the actual Docker container logs? I noticed the issue for me showed up in the logs for the Next.js container, not directly in the inspect element console

**Comment by ckifer** [comment]
well I did run into a different error with 3.2 😅. But yes the dockerfile logs in 3.1 are clean

**Comment by Moepkid** [comment]
Hey! We currently get an error after updating next from 15.5.3 to, react to 19.1.1. This is with recharts 3.2

```
## Error Type
Runtime TypeError

## Error Message
(0 , _toolkit.createSlice) is not a function


    at (pages-dir-node)/../../node_modules/recharts/lib/state/layoutSlice.js (.next\server\vendor-chunks\recharts.js:1050:1)
    at (pages-dir-node)/../../node_modules/recharts/lib/context/chartLayoutContext.js (.next\server\vendor-chunks\recharts.js:650:1)
    at (pages-dir-node)/../../node_modules/recharts/lib/component/Legend.js (.next\server\vendor-chunks\recharts.js:500:1)
    at (pages-dir-node)/../../node_modules/recharts/lib/index.js (.next\server\vendor-chunks\recharts.js:720:1)
    at eval (webpack-internal:///(pages-dir-node)/../../packages/app/src/molecules/DonutChart/DonutChart.tsx:9:107)
    at eval (webpack-internal:///(pages-dir-node)/../../packages/app/src/molecules/DonutChart/DonutChart.tsx:1:21)

Next.js version: 15.5.3 (Webpack)
```

adding the following does not work for us.

```
 outputFileTracingIncludes: {
    "*": [
      "../../node_modules/@reduxjs/toolkit/dist/**/*",
      "../../node_modules/immer/dist/**/*",
      "../../node_modules/reselect/dist/**/*",
      "../../node_modules/redux/dist/**/*",
      "../../node_modules/redux-thunk/dist/**/*",
    ],
  },
```

**Comment by marko-hologram** [comment]
It seems that Next.js is the issue here and only if using Pages Router as concluded above in some comments.
I've tried next v15.4.0 and this isn't an issue. Trying 15.4.1 and this issue appears.

So in 15.4.0 `node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs` does get output to standalone folder, in 15.4.1 it does not. I've tested it by just installing different nextjs version and then running the build. No code was changed while I was testing this and recharts version used was 3.1.2, even though that doesn't impact things because I haven't touched that.

**Comment by graup** [comment]
I also ran into this error. I'm **not** using Next.js, I'm on Tanstack Start v 1.121.1. I upgraded recharts from 2.15.0 to 3.2.1.

It works fine in `dev` mode but fails when I run `build` with target: "node-server". I'll try to make a repro for this.

**Comment by mackattack3k** [comment]
> I also ran into this error. I'm **not** using Next.js, I'm on Tanstack Start v 1.121.1. I upgraded recharts from 2.15.0 to 3.2.1.
> 
> It works fine in `dev` mode but fails when I run `build` with target: "node-server". I'll try to make a repro for this.

I have almost the same issue but I am using Bun 1.2.23 if that matters. It compiles to a stand-alone CJS bundle with `bun build --format=cjs".

This is the error I get in production
```
{
  "textPayload": "TypeError: Expected CommonJS module to have a function wrapper. If you weren't messing around with Bun's internals, this is a bug in Bun\n      at anonymous (unknown:1:1)\n      at /app/node_modules/@reduxjs/toolkit/dist/cjs/index.js:3:10\n      at anonymous (unknown:1:1)\n      at /app/node_modules/recharts/lib/state/layoutSlice.js:7:1\n      at anonymous (unknown:1:1)\n      at /app/node_modules/recharts/lib/context/chartLayoutContext.js:9:1\n      at anonymous (unknown:1:1)\n      at /app/node_modules/recharts/lib/component/Legend.js:16:1\n      at anonymous (unknown:1:1)\n      at /app/node_modules/recharts/lib/index.js:392:1",
  "insertId": "68e3b5260003a815fac0a102",
  "resource": {
    "type": "cloud_run_revision",
  },
  "timestamp": "2025-10-06T12:25:10.239637Z",
  "severity": "ERROR",
  ]
}```

**Comment by zGrav** [comment]
hey folks, fwiw, i was able to get things to run on my end using:

```
    // recharts is acting up with @reduxjs/toolkit, so i'm forcing it to use CJS instead so it doesn't bail on TypeError: (0, _toolkit.createSlice) is not a function
    config.resolve.alias['@reduxjs/toolkit'] = require.resolve(
      '@reduxjs/toolkit/dist/index.js'
    );
```

still testing to make sure i didn't break anything else though, so your mileage may vary.

current versions used:
```
    "@reduxjs/toolkit": "^1.9.7",
    "next": "15.5.5",
    "recharts": "^3.3.0",
```

edit: was able to not need this by setting `esmExternals: false` in experimental.

**Comment by charliematters** [comment]
I was seeing this too just in vitest - not using Next.JS.
For some reason the [resolve update from zGrav ](https://github.com/recharts/recharts/issues/6117#issuecomment-3461370335), didn't work for me, but forcing recharts to resolve to the module export did:

```
config.resolve.alias = [
  {
    find: 'recharts',
    replacement: 'recharts/es6/index.js',
  }
]
```

I notice there isn't an exports object in the package.json - perhaps it's related to that?

**Comment by guisehn** [comment]
We build our Next.js app with `output` = `standalone`, and were coming across the error:

```
Cannot find module [...]/node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs
```

We were able to solve it using the same solution that @iffa mentioned above in the thread, but with a few differences. In our case, the config needed was:

```js
  outputFileTracingIncludes: {
    '**/*': [
      'node_modules/@reduxjs/toolkit/dist/**/*',
      'node_modules/@reduxjs/toolkit/node_modules/**/*',
      'node_modules/redux/dist/**/*',
      'node_modules/redux-thunk/dist/**/*',
    ],
  },
```

I think each app might need a different config. In our case for example, `immer` is included inside `@reduxjs/toolkit/node_modules` instead of root `node_modules`, so the config needed was a bit different.

A tip for reducing the feedback loop when fixing your app is:

1. `next build` your app
2. `cd .next/standalone && node server.js`
3. Open the page that includes `recharts`
4. If the issue is not solved, you'll still see `Cannot find module [...]` in your terminal. Take note of what module is missing, and adjust your `next.config.js` accordingly, then restart the steps from the beginning (you'll need to `next build` again)

**Note:** If your page requires env vars to work properly, it'll probably crash when running Next.js this way via `node server.js`, as it won't include any env vars from your local `.env` files. In our case, I just kept adjusting `next.config.js`, rebuilding, and retrying until `Cannot find module [...]` was no longer shown in the terminal when opening the page.

**Comment by ckifer** [comment]
I still find it wild that this can't be reliably reproduced

**Comment by guisehn** [comment]
@ckifer I built a minimum reproducible example of the issue, if it helps:

https://github.com/guisehn/recharts-nextjs-issue-mre

**Comment by ckifer** [comment]
@guisehn looks like that repo is private

**Comment by guisehn** [comment]
@ckifer Sorry! It's public now

**Comment by ckifer** [comment]
thanks @guisehn I can repro! FYI @PavelVanecek

**Comment by PavelVanecek** [comment]
So looks like that https://github.com/vercel/nft gets confused by our setup and conveniently forgets to include the various ESM files when building the standalone server.

If I added exports to our package.json like this:

```json
  "exports": {
    ".": {
      "types": "./types/index.d.ts",
      "import": "./es6/index.js",
      "require": "./lib/index.js"
    },
    "./es6/*": "./es6/*.js",
    "./lib/*": "./lib/*.js"
  },
```

then the nextjs problem goes away but everything webpack and React16-17 breaks.

I can workaround this problem by adding the appropriate files back where nft forgot to copy:

```sh
cp node_modules/@reduxjs/toolkit/dist/redux-toolkit.modern.mjs .next/standalone/node_modules/@reduxjs/toolkit/dist
cp node_modules/redux/dist/redux.mjs .next/standalone/node_modules/redux/dist
cp node_modules/@reduxjs/toolkit/node_modules/immer/dist/immer.mjs .next/standalone/node_modules/@reduxjs/toolkit/node_modules/immer/dist
cp node_modules/reselect/dist/reselect.mjs .next/standalone/node_modules/reselect/dist
cp node_modules/redux-thunk/dist/redux-thunk.mjs .next/standalone/node_modules/redux-thunk/dist
```

Then the errors go away. The chart still doesn't render for reasons I don't fully understand, there's something special going on with next.js that I haven't discovered yet.

Interesting thing is that I can't reproduce this with redux alone, not v1 nor v2.

I suspect that `outputFileTracingIncludes` (https://github.com/recharts/recharts/issues/6117#issuecomment-3660951539) and/or `config.resolve.alias` (https://github.com/recharts/recharts/issues/6117#issuecomment-3461370335, https://github.com/recharts/recharts/issues/6117#issuecomment-3585422461) are doing the same thing.

I don't see what we can do with this in Recharts 3.x.
- We can move everything to ESM only and drop React 16-17, and drop Webpack in Recharts 4. That will make Webpack people seriously unhappy I imagine.
- Or we can keep this as-is with workarounds.
- Or we can ask vercel what are we supposed to do to have vercel/nft copy the ESM files.

**Comment by ckifer** [comment]
Nice find @PavelVanecek !

**Comment by battaglr** [comment]
Experiencing the exact same issue, using Recharts v3, Next.js v15 (pages router), and React v19.2.

These 2 workarounds worked for me:
- Add `outputFileTracingIncludes`, or
- Downgrade to Next.js v15.4.0.

> Or we can ask vercel what are we supposed to do to have vercel/nft copy the ESM files.

How can we help to make this happen?

**Comment by PavelVanecek** [comment]
@battaglr do you know someone at Vercel? I haven't tried creating an issue in one of their repositories yet - but seeing they have thousands opened issues, years old, it gives me low confidence that will get us far. But I haven't tried yet.

**Comment by battaglr** [comment]
@PavelVanecek

> I haven’t tried creating an issue in one of their repositories yet

If I’m following correctly, this looks like an issue in [nft](https://github.com/vercel/nft). That repo only has 38 open issues and 7 PRs, which is reassuring 😅

Since you clearly know more about this than I do, would you be up for opening an issue there?

> do you know someone at Vercel?

If we don’t get a response, I can reach out to a few folks, but let’s first see how it goes once the issue is open.

**Comment by LovelessCodes** [comment]
Just want to chime in and tell you guys, that it's not only on Next, it also happens in TanStack Start.

**Comment by PavelVanecek** [comment]
@LovelessCodes would you like to contribute a reproduction? I tried and could not find the problem: https://github.com/recharts/recharts-integ/tree/main/integrations/tanstack-start-basic

**Comment by LovelessCodes** [comment]
> [@LovelessCodes](https://github.com/LovelessCodes) would you like to contribute a reproduction? I tried and could not find the problem: https://github.com/recharts/recharts-integ/tree/main/integrations/tanstack-start-basic

I'll try to make a reproduction - full transparency; I migrated a NextJS application to TanStack Start, and only then got the error.

**Comment by battaglr** [comment]
@LovelessCodes were you able to repro?

**Comment by lukas-cc** [comment]
Maybe this will help someone, at least it was the root cause for me... I was on node version 22.12.0. locally. Upgrading the node version (I believe 23.x or above) resolved the issue.

**Comment by EfstathiadisD** [comment]
I had the same issue today. Dev worked like a charm, but production failed. I would suggest to drop CJS support and go towards ESM only in v4. It's time. Vercel is to blame here for sure, but I think it's time to move to ESM.
