### ISSUE TITLE
_toolkit.createSlice error when running in nextjs 15 on react 19

### ISSUE THREAD

**Issue by Moepkid** [recharts/recharts#6316]
## What is the current behavior?

Hey! We currently get an error after updating next from 15.5.3 to, react to 19.1.1. This is with recharts 3.2

```
## Error Type
Runtime TypeError

## Error Message
(0 , _toolkit.createSlice) is not a function


    at (pages-dir-node)/../../node_modules/recharts/lib/state/layoutSlice.js (.next\server\vendor-chunks\recharts.js:1050:1)
    at (pages-dir-node)/../../node_modules/recharts/lib/context/chartLayoutContext.js (.next\server\vendor-chunks\recharts.js:650:1)
    at (pages-dir-node)/../../node_modules/recharts/lib/component/Legend.js (.next\server\vendor-chunks\recharts.js:500:1)
    at (pages-dir-node)/../../node_modules/recharts/lib/index.js (.next\server\vendor-chunks\recharts.js:720:1)
    at eval (webpack-internal:///(pages-dir-node)/../../packages/app/src/molecules/DonutChart/DonutChart.tsx:9:107)
    at eval (webpack-internal:///(pages-dir-node)/../../packages/app/src/molecules/DonutChart/DonutChart.tsx:1:21)

Next.js version: 15.5.3 (Webpack)
```

adding the following does not work for us.

```
 outputFileTracingIncludes: {
    "*": [
      "../../node_modules/@reduxjs/toolkit/dist/**/*",
      "../../node_modules/immer/dist/**/*",
      "../../node_modules/reselect/dist/**/*",
      "../../node_modules/redux/dist/**/*",
      "../../node_modules/redux-thunk/dist/**/*",
    ],
  },
```

## What is the expected behavior?

No error.

## Which versions of Recharts, and which browser / OS are affected by this issue? Did this work in previous versions of Recharts?

It worked before the upgrade of nextjs and react. We were on nextjs 14 and react 18

**Comment by ckifer** [comment]
Does 3.1.2 work and just not 3.2? Or anything 3.x doesn't work?

**Comment by Moepkid** [comment]
Hey! Thanks for replying. It's also on 3.1 (I just checked).

**Comment by ckifer** [comment]
hey @Moepkid, no problem - can you give me similar info to what the others were giving in the other thread? 

* What does your next config look like (remove anything that is company/project internal)
* TS config
* what package manager (and version of that)
* when specifically does this happen (running dev server, on build, etc)
* what was your upgrade path? Did you upgrade next first and then try to upgrade recharts? What recharts version were you on before?

apologies for all the questions but these issues are tricky :D

**Comment by Moepkid** [comment]
No apologies man! I will get back to you in a bit and provide the information.

**Comment by Moepkid** [comment]
Here is the info!

Our next config:

```
const jssConfig = require("./src/temp/config").default;
const plugins = require("./src/temp/next-config-plugins") || {};
const publicUrl = jssConfig.publicUrl;

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  output: "standalone",
  transpilePackages: [
  ],
  // Set assetPrefix to our public URL
  assetPrefix: publicUrl,

  // Allow specifying a distinct distDir when concurrently running app in a container
  distDir: process.env.NEXTJS_DIST_DIR || ".next",

  // Make the same PUBLIC_URL available as an environment variable on the client bundle
  env: {
    PUBLIC_URL: publicUrl,
  },

  i18n: {
    // These are all the locales you want to support in your application.
    // These should generally match (or at least be a subset of) those in Sitecore.
    locales: ["nl-NL"],
    // This is the locale that will be used when visiting a non-locale
    // prefixed path e.g. `/styleguide`.
    defaultLocale: jssConfig?.defaultLanguage ?? "nl-NL",
  },

  compiler: {
    reactRemoveProperties: { properties: ["^data-testid$"] },
  },

  // Enable React Strict Mode
  reactStrictMode: true,

  // use this configuration to ensure that only images from the whitelisted domains
  // can be served from the Next.js Image Optimization API
  // see https://nextjs.org/docs/app/api-reference/components/image#remotepatterns
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "edge*.**",
        port: "",
      },
      {
        protocol: "https",
        hostname: "feaas*.blob.core.windows.net",
        port: "",
      },
    ],
  },

  async rewrites() {
    // When in connected mode we want to proxy Sitecore paths off to Sitecore
    return [
      // API endpoints
      // healthz check
      {
        source: "/healthz",
        destination: "/api/healthz",
      },
      // rewrite for Sitecore service pages
      {
        source: "/sitecore/service/:path*",
        destination: `${jssConfig.sitecoreApiHost}/sitecore/service/:path*`,
      },
      // visitor identification
      {
        source: "/layouts/system/:path*",
        destination: `${jssConfig.sitecoreApiHost}/layouts/system/:path*`,
      },
    ];
  },

  // test
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
        ],
      },
    ];
  },
};

module.exports = () => {
  // Run the base config through any configured plugins
  return Object.values(plugins).reduce(
    (acc, plugin) => plugin(acc),
    nextConfig,
  );
};
```

Our ts config (extension + base)

```
{
  "extends": "../../base.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "assets/*": ["src/assets/*"],
      "components/*": ["src/components/*"],
      "@constants/*": ["src/constants/*"],
      "context/*": ["src/context/*"],
      "hooks/*": ["src/hooks/*"],
      "lib/*": ["src/lib/*"],
      "pages/*": ["src/pages/*"],
      "temp/*": ["src/temp/*"],
      "types/*": ["src/types/*"],
      "utils/*": ["src/utils/*"],
      "mocks/*": ["src/__tests__/__mocks__/*"],
      "react": ["node_modules/react"]
    },
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "strictFunctionTypes": false,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "strictNullChecks": false
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "vite.config.ts"
  ],
  "exclude": ["node_modules", "storybook-static"]
}

```

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "types": ["node"],
    "allowJs": true,
    "composite": false,
    "declaration": false,
    "declarationMap": false,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSources": false,
    "incremental": false,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "preserveSymlinks": false,
    "preserveWatchOutput": true,
    "skipLibCheck": true,
    "strict": false,
    "target": "es5",
  },
  "include": ["declarations.d.ts"],
  "exclude": ["node_modules"]
}

```

package manager is NPM 11.6.0, node 24.8.0

This is happening on runtime, building is going completely fine.

We upgraded next and react together. We did not have any breaking changes affect us. We upgraded recharts after, we were on 3.1.0.

**Comment by ckifer** [comment]
Very interesting, especially the last part. Thanks for the info, it'll take a little bit to try a few things

**Comment by Moepkid** [comment]
Alright man! Thanks for your effort. Let me know if i have to share more information

**Comment by ckifer** [comment]
Ok so I 

* created a new next14 project with standalone output and some other of your settings that might be applicable
* added recharts 3.1 and got it running fine
* upgraded to next 15 and react 19 at the same time and got that running
* installed recharts 3.2

I'm running into this atm
> ReferenceError: window is not defined
    at b.createRechartsStore (.next/server/chunks/284.js:1:115145)
    at b.RechartsStoreProvider (.next/server/chunks/284.js:1:213462)

which is a known bug. I'm going to release 3.2.1 I think to fix that one

**Comment by Moepkid** [comment]
Aaah, alright maybe a caching issue on my part when I checked 3.1 after 3.2. I will let you know if 3.2.1 fixes the stuff. Thanks man, for getting back at me so quickly! Can I keep this issue open untill you release the bugfix?

**Comment by ckifer** [comment]
3.2.1 is released now but I don't think it'll solve your issue unfortunately.

What is interesting is: everything works normally until I upgraded to 3.2 from 3.1 but it breaks the same for me as the other issue. Which is, running the standalone server with `.next/standalone/server.js` just renders a white screen with no errors and no feedback.

@Moepkid how are you getting this error at runtime? in `next dev` or after build and run with `.next/standalone/server.js`?

**Comment by Moepkid** [comment]
We are getting the error at runtime with next dev!

**Comment by ckifer** [comment]
In that case, everything is working for me with no issues using next dev 🙃

These issues are so mind boggling because I can't reproduce

**Comment by Moepkid** [comment]
Yeah, the new versions doesnt fix it sadly. I will try and do a clean upgrade path again and update this ticket

**Comment by Moepkid** [comment]
Problem is, Sitecore jss 22.7 expects next and react to be updated both. So I wonder how we can best approach this issue. You have any suggestions?

**Comment by ckifer** [comment]
If we can get to a minimal reproduction I will look for a solution. But I can't spend a ton of time trying to reproduce since everything is working in a new project. 

My hunch is it has something to do with your lock file and the very specific upgrade path. Either that or is has to do with ES module resolution. Or both. 

You could try deleting your lock file and reinstalling and see if things work (just as a test)

I can keep noodling on what might help

**Comment by ckifer** [comment]
This issue https://github.com/reduxjs/redux-toolkit/issues/4474#issuecomment-2192683747 is kind of similar but not

It's the right kind of thinking though. Something isn't getting bundled/handled right. Problem is we don't do the bundling 😅

**Comment by Moepkid** [comment]
Yeah I saw that! thanks, will follow your insights and will let you know. You can close this issue if you want, but I am planning to provide an update for future developers who run into this issue (or AI tooling tot generate from haha)

**Comment by ckifer** [comment]
I'll keep it open for now since your issue is slightly different than the other

**Comment by gwkline** [comment]
Running into this myself, happening as I'm doing a migrations from `npm` to `pnpm`. 

~~I'm thinking this could be related?~~ Edit: I've tried overriding here to below 2.8.2 but can't get it working, might not be related
https://github.com/reduxjs/redux-toolkit/compare/v2.8.1...v2.8.2
https://github.com/reduxjs/redux-toolkit/releases/tag/v2.8.2

**Comment by gwkline** [comment]
As an update here, it seems like adding the package `@reduxjs/toolkit` as a direct dependency of our Next app resolves the issue. Not sure why the recharts transitive dependency is not sufficient, but hope this can help!

**Comment by Moepkid** [comment]
Hey! We did this also but its not working. Can you share what you did?

**Comment by zGrav** [comment]
Hey folks,

as posted on: https://github.com/recharts/recharts/issues/6117#issuecomment-3461370335

fwiw, i was able to get things to run on my end using:

```
    // recharts is acting up with @reduxjs/toolkit, so i'm forcing it to use CJS instead so it doesn't bail on TypeError: (0, _toolkit.createSlice) is not a function
    config.resolve.alias['@reduxjs/toolkit'] = require.resolve(
      '@reduxjs/toolkit/dist/index.js'
    );
```

still testing to make sure i didn't break anything else though, so your mileage may vary.

current versions used:
```
    "@reduxjs/toolkit": "^1.9.7",
    "next": "15.5.5",
    "recharts": "^3.3.0",
```

edit: was able to not need this by setting `esmExternals: false` in experimental.
