### ISSUE TITLE
Rotated Axis labels

### ISSUE THREAD

**Issue by Eric24** [recharts/recharts#466]
It would be great to have support for axis labels that appear rotated, to the left/right of a Y-axis or the top/bottom of an X-axis. See this link for an example: [Rotated Axis Labels](http://www.highcharts.com/demo/combo-dual-axes)

**Comment by akvanhar** [comment]
I would like this too - I don't use your axis labels for just this reason.

**Comment by xile611** [comment]
@Eric24 It's recommended to use `<Text />` to render label.

**Comment by Eric24** [comment]
Well, OK, but that feels like a workaround to me. Since axes already have labels (which the should--it's an inherent feature of an axis), I think it should be possible to specify how/where the label is drawn. IMHO, the current (exclusive) default of horizontal text at the end of the axis is just about the least likely place the label should be.

**Comment by su-narthur** [comment]
@xile611 This gives me this error:

> [at-loader] ./src/components/molecules/cohortTable.tsx:21:39 
>     TS2339: Property 'angle' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<XAxis> & Readonly<{ children?: ReactNode; }> & Rea...'.

This is the version of Recharts I'm doing (from package.json):

`"recharts": "^1.0.0-alpha.4"`

**Comment by Harokku** [comment]
@su-narthur 

`<XAxis dataKey='name' angle={-45} textAnchor='end'/>` work in `"recharts": "^1.0.0-apha.5"`

recharts site indicate alpha.4 as last version, but alpha.5 it's already availabe in npm at the time of writing.

Try an update

**Comment by nhooey** [comment]
I get this error with recharts `^1.0.0-alpha.6`:
```
Warning: Unknown prop `angle` on <line> tag.
Remove this prop from the element.
For details, see https://fb.me/react-unknown-prop
```
From this code:
```jsx
<YAxis label={this.props.yAxisLabel} dataKey="value"
       domain={this.props.yAxisDomain}
       angle={-45} textAnchor="end" />
```

**Comment by nhooey** [comment]
And how do you angle the Y-axis _label_?

**Comment by alyssaq** [comment]
```
<YAxis>
   <Label angle={-90} value='custom label' position='insideLeft' style={{textAnchor: 'middle'}} />
</YAxis>
```
<img width="276" alt="screen shot 2017-10-31 at 12 45 11 pm" src="https://user-images.githubusercontent.com/2819448/32207812-69954ba2-be39-11e7-91ff-2873e1fc3e76.png">

**Comment by fengshuo** [comment]
I was following other issues and it is using the `angle` prop. But I got this warning:
`Warning: Unknown prop `angle` on <line> tag. Remove this prop from the element`

xaxis:
```
<XAxis
              dataKey="name"
              interval={0}
              angle={-35}
              textAnchor="end"
            />
```

**Comment by dylhunn** [comment]
I still get the unknown prop error when trying to use `angle` on `XAxis`.

**Comment by pjmartins** [comment]
Getting the same error, Unknown prop angle on <line> tag. Remove this prop from the element

`<ResponsiveContainer height={300}>
		<BarChart data={data}>
			<CartesianGrid strokeDasharray="3 3" />
			<XAxis dataKey="name" angle={-45} textAnchor="end">
			</XAxis>
			<YAxis />
			<Legend />
			<Tooltip />
			<Bar name="Value1" dataKey="Value1" fill="#A40000" />
			<Bar name="Value2" dataKey="Value2" fill="#8884d8" />
		</BarChart>
	</ResponsiveContainer>
`

**Comment by SachinKr57** [comment]
@nhooey This warning can be solved by
<XAxis
            dataKey="name"
            textAnchor="end"
            **tick={{ angle: 45 }}**
          />

**Comment by Wataru0412** [comment]
@SachinKr57; 
That works nicely! You saved my weekend. Thanks.

**Comment by spjpgrd** [comment]
Just adding on to this, as it's somewhat related.

I'm trying to rotate tick value text at certain breakpoints. Trying to do this through CSS might not be feasible, as using `transform` rotates the tick value relative to the entire `.rechart-surface` svg — leading to some fun results.

Can only seem to effect the `.recharts-cartesian-axis-tick-value` `text` element with `transform`, but the `tspan` child element doesn't respond to the transform (but it does with other CSS properties, like `font-family`, and `font-size`

An example of rotating it `-6 degrees`:
<img width="349" alt="Chart label floating in the middle of the chart" src="https://user-images.githubusercontent.com/5985948/53590263-61c8eb00-3b5f-11e9-8dc1-853f1824cc3f.png">

**Comment by chaudev** [comment]
in 2024  `<XAxis dataKey="name" angle={-45} textAnchor="end" />`

**Comment by shriekdj** [comment]
> ```js
> <XAxis dataKey="name" angle={-45} textAnchor="end" />
> ```
> 
> @Eric24 Use the props angle and textAnchor in XAxis. The feature has been done in 1.0.0+.

thanks
